before_script:
  - hostname
  - whoami
  - pwd
  - ls -la
  - docker --version

stages:
   - build
   - test
   - coverage
   - deploy
   - test-deployment

build:
  tags:
     - ece651
  stage: build
  script: 
    - cd attendance-management
    - docker build --build-arg LOCAL_USER_ID=`id -u` --tag citest .

test:
  tags:
     - ece651
  stage: test
  coverage: '/TOTAL COVERAGE: \d+\%/'
  script:
    - chmod +x attendance-management/scripts/run-tests-in-docker.sh
    - chmod +x attendance-management/scripts/test.sh
    - chmod +x attendance-management/scripts/coverage_summary.sh
    - attendance-management/scripts/run-tests-in-docker.sh
  artifacts:
    paths:
      - coverage
      
pages:
 stage: coverage
 tags:
     - ece651
 dependencies:
   - test
 script:
   - mv coverage public/
 artifacts:
   paths:
     - public

deploy:
  tags:
    - ece651
  stage: deploy
  script: 
    - chmod +x attendance-management/scripts/redeploy.sh
    - ./attendance-management/scripts/redeploy.sh
