/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.shared;

import static org.junit.jupiter.api.Assertions.*;

import java.io.BufferedReader;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.io.PrintStream;
import java.io.StringReader;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;

import org.junit.jupiter.api.Test;

@Disabled 
class AppTest {

}
