/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.userAdmin;

public class App {
    public String getGreeting() {
        return "Hello World! from userAdmin";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
