/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.userAdmin;

import java.io.BufferedReader;
import java.io.InputStreamReader;

import edu.duke.ece651.userAdmin.AdminTextView;

public class App {
    public static void main(String[] args) {
        BufferedReader inputReader = new BufferedReader(new InputStreamReader(System.in));
        //AdminTextView.start(inputReader, System.out);
    }
}
