/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.courseManage;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;


public class App {

  public static void main(String[] args) throws IOException {
    System.out.println("\n******************************************\n" +
                       "Welcome to the Course Management App!\n" +
                       "******************************************\n");
    BufferedReader inputReader = new BufferedReader(new InputStreamReader(System.in));
    courseManager CourseManager = new courseManager(inputReader, System.out);
    //CourseManager.createCourse(inputReader, System.out);
    try {
      CourseManager.loop();
    }
    catch(Exception e) {
      System.exit(0);
    }
    System.exit(0);
  }
}

